const objKeyEn = {
  Backquote: { key: '`', shiftkey: '~', CapsLock: '`', keycode: 192 },
  Digit1: { key: '1', shiftkey: '!', CapsLock: '1', keycode: 49 },
  Digit2: { key: '2', shiftkey: '@', CapsLock: '2', keycode: 50 },
  Digit3: { key: '3', shiftkey: '#', CapsLock: '3', keycode: 51 },
  Digit4: { key: '4', shiftkey: '$', CapsLock: '4', keycode: 52 },
  Digit5: { key: '5', shiftkey: '%', CapsLock: '5', keycode: 53 },
  Digit6: { key: '6', shiftkey: '^', CapsLock: '6', keycode: 54 },
  Digit7: { key: '7', shiftkey: '&', CapsLock: '7', keycode: 55 },
  Digit8: { key: '8', shiftkey: '*', CapsLock: '8', keycode: 56 },
  Digit9: { key: '9', shiftkey: '(', CapsLock: '9', keycode: 57 },
  Digit0: { key: '0', shiftkey: ')', CapsLock: '0', keycode: 48 },
  Minus: { key: '-', shiftkey: '_', CapsLock: '-', keycode: 189 },
  Equal: { key: '=', shiftkey: '+', CapsLock: '=', keycode: 187 },
  Backspace: {
    key: 'Backspace',
    shiftkey: 'Backspace',
    CapsLock: 'Backspace',
    keycode: 8,
  },
  Tab: { key: 'Tab', shiftkey: 'Tab', CapsLock: 'Tab', keycode: 9 },
  KeyQ: { key: 'q', shiftkey: 'Q', CapsLock: 'Q', keycode: 81 },
  KeyW: { key: 'w', shiftkey: 'W', CapsLock: 'W', keycode: 87 },
  KeyE: { key: 'e', shiftkey: 'E', CapsLock: 'E', keycode: 69 },
  KeyR: { key: 'r', shiftkey: 'R', CapsLock: 'R', keycode: 82 },
  KeyT: { key: 't', shiftkey: 'T', CapsLock: 'T', keycode: 84 },
  KeyY: { key: 'y', shiftkey: 'Y', CapsLock: 'Y', keycode: 89 },
  KeyU: { key: 'u', shiftkey: 'U', CapsLock: 'U', keycode: 85 },
  KeyI: { key: 'i', shiftkey: 'I', CapsLock: 'I', keycode: 73 },
  KeyO: { key: 'o', shiftkey: 'O', CapsLock: 'O', keycode: 79 },
  KeyP: { key: 'p', shiftkey: 'P', CapsLock: 'P', keycode: 80 },
  BracketLeft: { key: '[', shiftkey: '{', CapsLock: '[', keycode: 219 },
  BracketRight: { key: ']', shiftkey: '}', CapsLock: ']', keycode: 221 },
  Backslash: { key: '\\', shiftkey: '|', CapsLock: '\\', keycode: 220 },
  Delete: { key: 'Del', shiftkey: 'Del', CapsLock: 'Del', keycode: 46 },
  CapsLock: {
    key: 'CapsLock',
    shiftkey: 'CapsLock',
    CapsLock: 'CapsLock',
    keycode: 20,
  },
  KeyA: { key: 'a', shiftkey: 'A', CapsLock: 'A', keycode: 65 },
  KeyS: { key: 's', shiftkey: 'S', CapsLock: 'S', keycode: 83 },
  KeyD: { key: 'd', shiftkey: 'D', CapsLock: 'D', keycode: 68 },
  KeyF: { key: 'f', shiftkey: 'F', CapsLock: 'F', keycode: 70 },
  KeyG: { key: 'g', shiftkey: 'G', CapsLock: 'G', keycode: 71 },
  KeyH: { key: 'h', shiftkey: 'H', CapsLock: 'H', keycode: 72 },
  KeyJ: { key: 'j', shiftkey: 'J', CapsLock: 'J', keycode: 74 },
  KeyK: { key: 'k', shiftkey: 'K', CapsLock: 'K', keycode: 75 },
  KeyL: { key: 'l', shiftkey: 'L', CapsLock: 'L', keycode: 76 },
  Semicolon: { key: ';', shiftkey: ':', CapsLock: ';', keycode: 186 },
  Quote: { key: "'", shiftkey: '"', CapsLock: "'", keycode: 222 },
  Enter: { key: 'Enter', shiftkey: 'Enter', CapsLock: 'Enter', keycode: 13 },
  ShiftLeft: {
    key: 'Shift',
    shiftkey: 'Shift',
    CapsLock: 'Shift',
    keycode: 16,
  },
  KeyZ: { key: 'z', shiftkey: 'Z', CapsLock: 'Z', keycode: 90 },
  KeyX: { key: 'x', shiftkey: 'X', CapsLock: 'X', keycode: 88 },
  KeyC: { key: 'c', shiftkey: 'C', CapsLock: 'C', keycode: 67 },
  KeyV: { key: 'v', shiftkey: 'V', CapsLock: 'V', keycode: 86 },
  KeyB: { key: 'b', shiftkey: 'B', CapsLock: 'B', keycode: 66 },
  KeyN: { key: 'n', shiftkey: 'N', CapsLock: 'N', keycode: 78 },
  KeyM: { key: 'm', shiftkey: 'M', CapsLock: 'M', keycode: 77 },
  Comma: { key: ',', shiftkey: '<', CapsLock: ',', keycode: 188 },
  Period: { key: '.', shiftkey: '>', CapsLock: '.', keycode: 190 },
  Slash: { key: '/', shiftkey: '?', CapsLock: '/', keycode: 191 },
  ArrowUp: { key: '▲', shiftkey: '▲', CapsLock: '▲', keycode: 38 },
  ShiftRight: {
    key: 'Shift',
    shiftkey: 'Shift',
    CapsLock: 'Shift',
    keycode: 16,
  },
  ControlLeft: { key: 'Ctrl', shiftkey: 'Ctrl', CapsLock: 'Ctrl', keycode: 17 },
  MetaLeft: { key: 'Win', shiftkey: 'Win', CapsLock: 'Win', keycode: 91 },
  AltLeft: { key: 'Alt', shiftkey: 'Alt', CapsLock: 'Alt', keycode: 18 },
  Space: { key: ' ', shiftkey: ' ', CapsLock: ' ', keycode: 32 },
  AltRight: { key: 'Alt', shiftkey: 'Alt', CapsLock: 'Alt', keycode: 18 },
  ArrowLeft: { key: '◄', shiftkey: '◄', CapsLock: '◄', keycode: 37 },
  ArrowDown: { key: '▼', shiftkey: '▼', CapsLock: '▼', keycode: 40 },
  ArrowRight: { key: '►', shiftkey: '►', CapsLock: '►', keycode: 39 },
  ControlRight: {
    key: 'Ctrl',
    shiftkey: 'Ctrl',
    CapsLock: 'Ctrl',
    keycode: 17,
  },
};
const objKeyRu = {
  Backquote: { key: 'ё', shiftkey: 'Ё', CapsLock: 'Ё', keycode: 192 },
  Digit1: { key: '1', shiftkey: '!', CapsLock: '1', keycode: 49 },
  Digit2: { key: '2', shiftkey: '"', CapsLock: '2', keycode: 50 },
  Digit3: { key: '3', shiftkey: '№', CapsLock: '3', keycode: 51 },
  Digit4: { key: '4', shiftkey: ';', CapsLock: '4', keycode: 52 },
  Digit5: { key: '5', shiftkey: '%', CapsLock: '5', keycode: 53 },
  Digit6: { key: '6', shiftkey: ':', CapsLock: '6', keycode: 54 },
  Digit7: { key: '7', shiftkey: '?', CapsLock: '7', keycode: 55 },
  Digit8: { key: '8', shiftkey: '*', CapsLock: '8', keycode: 56 },
  Digit9: { key: '9', shiftkey: '(', CapsLock: '9', keycode: 57 },
  Digit0: { key: '0', shiftkey: ')', CapsLock: '0', keycode: 48 },
  Minus: { key: '-', shiftkey: '_', CapsLock: '-', keycode: 189 },
  Equal: { key: '=', shiftkey: '+', CapsLock: '=', keycode: 187 },
  Backspace: {
    key: 'Backspace',
    shiftkey: 'Backspace',
    CapsLock: 'Backspace',
    keycode: 8,
  },
  Tab: { key: 'Tab', shiftkey: 'Tab', CapsLock: 'Tab', keycode: 9 },
  KeyQ: { key: 'й', shiftkey: 'Й', CapsLock: 'Й', keycode: 81 },
  KeyW: { key: 'ц', shiftkey: 'Ц', CapsLock: 'Ц', keycode: 87 },
  KeyE: { key: 'у', shiftkey: 'У', CapsLock: 'У', keycode: 69 },
  KeyR: { key: 'к', shiftkey: 'К', CapsLock: 'К', keycode: 82 },
  KeyT: { key: 'е', shiftkey: 'Е', CapsLock: 'Е', keycode: 84 },
  KeyY: { key: 'н', shiftkey: 'Н', CapsLock: 'Н', keycode: 89 },
  KeyU: { key: 'г', shiftkey: 'Г', CapsLock: 'Г', keycode: 85 },
  KeyI: { key: 'ш', shiftkey: 'Ш', CapsLock: 'Ш', keycode: 73 },
  KeyO: { key: 'щ', shiftkey: 'Щ', CapsLock: 'Щ', keycode: 79 },
  KeyP: { key: 'з', shiftkey: 'З', CapsLock: 'З', keycode: 80 },
  BracketLeft: { key: 'х', shiftkey: 'Х', CapsLock: 'Х', keycode: 219 },
  BracketRight: { key: 'ъ', shiftkey: 'Ъ', CapsLock: 'Ъ', keycode: 221 },
  Backslash: { key: '\\', shiftkey: '\\', CapsLock: '\\', keycode: 220 },
  Delete: { key: 'Del', shiftkey: 'Del', CapsLock: 'Del', keycode: 46 },
  CapsLock: {
    key: 'CapsLock',
    shiftkey: 'CapsLock',
    CapsLock: 'CapsLock',
    keycode: 20,
  },
  KeyA: { key: 'ф', shiftkey: 'Ф', CapsLock: 'Ф', keycode: 65 },
  KeyS: { key: 'ы', shiftkey: 'Ы', CapsLock: 'Ы', keycode: 83 },
  KeyD: { key: 'в', shiftkey: 'В', CapsLock: 'В', keycode: 68 },
  KeyF: { key: 'а', shiftkey: 'А', CapsLock: 'А', keycode: 70 },
  KeyG: { key: 'п', shiftkey: 'П', CapsLock: 'П', keycode: 71 },
  KeyH: { key: 'р', shiftkey: 'Р', CapsLock: 'Р', keycode: 72 },
  KeyJ: { key: 'о', shiftkey: 'О', CapsLock: 'О', keycode: 74 },
  KeyK: { key: 'л', shiftkey: 'Л', CapsLock: 'Л', keycode: 75 },
  KeyL: { key: 'д', shiftkey: 'Д', CapsLock: 'Д', keycode: 76 },
  Semicolon: { key: 'ж', shiftkey: 'Ж', CapsLock: 'Ж', keycode: 186 },
  Quote: { key: 'э', shiftkey: 'Э', CapsLock: 'З', keycode: 222 },
  Enter: { key: 'Enter', shiftkey: 'Enter', CapsLock: 'Enter', keycode: 13 },
  ShiftLeft: {
    key: 'Shift',
    shiftkey: 'Shift',
    CapsLock: 'Shift',
    keycode: 16,
  },
  KeyZ: { key: 'я', shiftkey: 'Я', CapsLock: 'Я', keycode: 90 },
  KeyX: { key: 'ч', shiftkey: 'Ч', CapsLock: 'Ч', keycode: 88 },
  KeyC: { key: 'с', shiftkey: 'С', CapsLock: 'С', keycode: 67 },
  KeyV: { key: 'м', shiftkey: 'М', CapsLock: 'М', keycode: 86 },
  KeyB: { key: 'и', shiftkey: 'И', CapsLock: 'И', keycode: 66 },
  KeyN: { key: 'т', shiftkey: 'Т', CapsLock: 'Т', keycode: 78 },
  KeyM: { key: 'ь', shiftkey: 'Ь', CapsLock: 'Ь', keycode: 77 },
  Comma: { key: 'б', shiftkey: 'Б', CapsLock: 'Б', keycode: 188 },
  Period: { key: 'ю', shiftkey: 'Ю', CapsLock: 'Ю', keycode: 190 },
  Slash: { key: '.', shiftkey: ',', CapsLock: '.', keycode: 191 },
  ArrowUp: { key: '▲', shiftkey: '▲', CapsLock: '▲', keycode: 38 },
  ShiftRight: {
    key: 'Shift',
    shiftkey: 'Shift',
    CapsLock: 'Shift',
    keycode: 16,
  },
  ControlLeft: { key: 'Ctrl', shiftkey: 'Ctrl', CapsLock: 'Ctrl', keycode: 17 },
  MetaLeft: { key: 'Win', shiftkey: 'Win', CapsLock: 'Win', keycode: 91 },
  AltLeft: { key: 'Alt', shiftkey: 'Alt', CapsLock: 'Alt', keycode: 18 },
  Space: { key: ' ', shiftkey: ' ', CapsLock: ' ', keycode: 32 },
  AltRight: { key: 'Alt', shiftkey: 'Alt', CapsLock: 'Alt', keycode: 18 },
  ArrowLeft: { key: '◄', shiftkey: '◄', CapsLock: '◄', keycode: 37 },
  ArrowDown: { key: '▼', shiftkey: '▼', CapsLock: '▼', keycode: 40 },
  ArrowRight: { key: '►', shiftkey: '►', CapsLock: '►', keycode: 39 },
  ControlRight: {
    key: 'Ctrl',
    shiftkey: 'Ctrl',
    CapsLock: 'Ctrl',
    keycode: 17,
  },
};

export { objKeyEn, objKeyRu };
