const objKeyEn = {
  Backquote: { key: '`', shiftkey: '~' },
  Digit1: { key: '1', shiftkey: '!' },
  Digit2: { key: '2', shiftkey: '@' },
  Digit3: { key: '3', shiftkey: '#' },
  Digit4: { key: '4', shiftkey: '$' },
  Digit5: { key: '5', shiftkey: '%' },
  Digit6: { key: '6', shiftkey: '^' },
  Digit7: { key: '7', shiftkey: '&' },
  Digit8: { key: '8', shiftkey: '*' },
  Digit9: { key: '9', shiftkey: '(' },
  Digit0: { key: '0', shiftkey: ')' },
  Minus: { key: '-', shiftkey: '_' },
  Equal: { key: '=', shiftkey: '+' },
  Backspace: {
    key: 'Backspace',
  },
  Tab: { key: 'Tab' },
  KeyQ: { key: 'q' },
  KeyW: { key: 'w' },
  KeyE: { key: 'e' },
  KeyR: { key: 'r' },
  KeyT: { key: 't' },
  KeyY: { key: 'y' },
  KeyU: { key: 'u' },
  KeyI: { key: 'i' },
  KeyO: { key: 'o' },
  KeyP: { key: 'p' },
  BracketLeft: { key: '[', shiftkey: '{' },
  BracketRight: { key: ']', shiftkey: '}' },
  Backslash: { key: '\\', shiftkey: '|' },
  Delete: { key: 'Del' },
  CapsLock: {
    key: 'CapsLock',
  },
  KeyA: { key: 'a' },
  KeyS: { key: 's' },
  KeyD: { key: 'd' },
  KeyF: { key: 'f' },
  KeyG: { key: 'g' },
  KeyH: { key: 'h' },
  KeyJ: { key: 'j' },
  KeyK: { key: 'k' },
  KeyL: { key: 'l' },
  Semicolon: { key: ';', shiftkey: ':' },
  Quote: { key: "'", shiftkey: '"' },
  Enter: { key: 'Enter' },
  ShiftLeft: {
    key: 'Shift',
  },
  KeyZ: { key: 'z' },
  KeyX: { key: 'x' },
  KeyC: { key: 'c' },
  KeyV: { key: 'v' },
  KeyB: { key: 'b' },
  KeyN: { key: 'n' },
  KeyM: { key: 'm' },
  Comma: { key: ',', shiftkey: '<' },
  Period: { key: '.', shiftkey: '>' },
  Slash: { key: '/', shiftkey: '?' },
  ArrowUp: { key: '▲' },
  ShiftRight: {
    key: 'Shift',
  },
  ControlLeft: { key: 'Ctrl' },
  Language: { key: 'EN' },
  AltLeft: { key: 'Alt' },
  Space: { key: 'Space' },
  AltRight: { key: 'Alt' },
  ArrowLeft: { key: '◄' },
  ArrowDown: { key: '▼' },
  ArrowRight: { key: '►' },
  ControlRight: {
    key: 'Ctrl',
  },
};
const objKeyRu = {
  Backquote: { key: 'ё', shiftkey: 'Ё' },
  Digit1: { key: '1', shiftkey: '!' },
  Digit2: { key: '2', shiftkey: '"' },
  Digit3: { key: '3', shiftkey: '№' },
  Digit4: { key: '4', shiftkey: ';' },
  Digit5: { key: '5', shiftkey: '%' },
  Digit6: { key: '6', shiftkey: ':' },
  Digit7: { key: '7', shiftkey: '?' },
  Digit8: { key: '8', shiftkey: '*' },
  Digit9: { key: '9', shiftkey: '(' },
  Digit0: { key: '0', shiftkey: ')' },
  Minus: { key: '-', shiftkey: '_' },
  Equal: { key: '=', shiftkey: '+' },
  Backspace: {
    key: 'Backspace',
  },
  Tab: { key: 'Tab' },
  KeyQ: { key: 'й' },
  KeyW: { key: 'ц' },
  KeyE: { key: 'у' },
  KeyR: { key: 'к' },
  KeyT: { key: 'е' },
  KeyY: { key: 'н' },
  KeyU: { key: 'г' },
  KeyI: { key: 'ш' },
  KeyO: { key: 'щ' },
  KeyP: { key: 'з' },
  BracketLeft: { key: 'х' },
  BracketRight: { key: 'ъ' },
  Backslash: { key: '\\', shiftkey: '/' },
  Delete: { key: 'Del' },
  CapsLock: {
    key: 'CapsLock',
  },
  KeyA: { key: 'ф' },
  KeyS: { key: 'ы' },
  KeyD: { key: 'в' },
  KeyF: { key: 'а' },
  KeyG: { key: 'п' },
  KeyH: { key: 'р' },
  KeyJ: { key: 'о' },
  KeyK: { key: 'л' },
  KeyL: { key: 'д' },
  Semicolon: { key: 'ж' },
  Quote: { key: 'э' },
  Enter: { key: 'Enter' },
  ShiftLeft: {
    key: 'Shift',
  },
  KeyZ: { key: 'я' },
  KeyX: { key: 'ч' },
  KeyC: { key: 'с' },
  KeyV: { key: 'м' },
  KeyB: { key: 'и' },
  KeyN: { key: 'т' },
  KeyM: { key: 'ь' },
  Comma: { key: 'б' },
  Period: { key: 'ю' },
  Slash: { key: '.', shiftkey: ',' },
  ArrowUp: { key: '▲' },
  ShiftRight: {
    key: 'Shift',
  },
  ControlLeft: { key: 'Ctrl' },
  Language: { key: 'RU' },
  AltLeft: { key: 'Alt' },
  Space: { key: 'Space' },
  AltRight: { key: 'Alt' },
  ArrowLeft: { key: '◄' },
  ArrowDown: { key: '▼' },
  ArrowRight: { key: '►' },
  ControlRight: {
    key: 'Ctrl',
  },
};

export { objKeyEn, objKeyRu };
